CONTIKI_PROJECT = plantio
all: $(CONTIKI_PROJECT)

PROJECT_SOURCEFILES += serial.c
PROJECT_SOURCEFILES += routing.c
PROJECT_SOURCEFILES += mote_sensors.c

CONTIKI_WITH_RIME = 1
CONTIKI = $(HOME)/.contiki
include $(CONTIKI)/Makefile.include